version: '3.8'

services:
  app:
    build: .
    container_name: acordo_app
    environment:
      DATABASE_URL: postgresql://postgres:1d0bce023c2dd458d2d3@homolog_postgres:5432/postgres-homolog
      PIN_USUARIO: "2425"
      PIN_PATRON:  "5678"
    volumes:
      - uploads_data:/app/uploads
    ports:
      - "8000:8000"
    restart: unless-stopped

volumes:
  uploads_data:
